services:
  s3-monitor:
    image: ghcr.io/jr200/nats-s3-monitor:local
    restart: unless-stopped
    user: root
    volumes:
    - ${NATS_USER_CREDENTIALS_FILE}:/secrets/app.creds:ro
    - ./secrets/config.yaml:/config.yaml:ro
    entrypoint:
    # - sleep
    # - 365d
    command:
      - -f
      - /config.yaml
    networks:
      - public-network
      - internal-network
    environment:
      # These are set by the .env.local file
      NATS_URL: ${NATS_INTERNAL_URL}
      NATS_USER_CREDENTIALS_FILE: /secrets/app.creds
      NATS_S3_MONITOR_SERVICE_ID: ${NATS_S3_MONITOR_SERVICE_ID}

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}

networks:
  public-network:
    name: ${EXTERNAL_NETWORK}
    external: true
  internal-network:
